name: nexo_mobile
description: "Nexo — plataforma financiera digital (app shell)."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  nexo_core:
    path: ../../packages/core
  nexo_design_system:
    path: ../../packages/design_system
  nexo_sdui_engine:
    path: ../../packages/sdui_engine
  flutter_bloc: ^9.1.1
  get_it: ^9.3.0
  go_router: ^18.0.2
  dio: ^5.11.1
  uuid: ^4.6.0
  intl: ^0.20.3
  connectivity_plus: ^6.1.4
  flutter_secure_storage: ^11.2.0
  shared_preferences: ^2.5.5
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  firebase_app_check: ^0.4.8
  firebase_crashlytics: ^5.4.0
  firebase_analytics: ^12.6.0
  firebase_performance: ^0.11.6
  firebase_remote_config: ^6.7.0
  flutter_localizations:
    sdk: flutter
  local_auth: ^3.0.2
  firebase_messaging: ^16.7.0
  flutter_local_notifications: ^22.0.0
  webview_flutter: ^4.14.1
  webview_flutter_android: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/sdui/
